### ISSUE TITLE
Take more time to process image

### ISSUE THREAD

**Issue by sagarzala123** [tumuyan/ESRGAN-Android-TFLite-Demo#1]
I am using a 110KB image with a 1200x800 height width. It takes 5 to 6 minutes to process image.

**Comment by tumuyan** [comment]
This is only a demo modify from https://github.com/tensorflow/examples/tree/master/lite/examples/super_resolution/android . Actually, it has a lot of problems. Maybe you could try this https://github.com/tumuyan/RealSR-NCNN-Android
